-- Migration: Add all missing columns to Gatepass table
-- Run this on your Railway MySQL database
-- Safe to run multiple times (uses IF NOT EXISTS / IGNORE)

ALTER TABLE Gatepass
    ADD COLUMN IF NOT EXISTS hr_approval VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS assigned_hr_code VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS hr_approved_by VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS hr_approval_date DATETIME NULL,
    ADD COLUMN IF NOT EXISTS hod_remark TEXT NULL,
    ADD COLUMN IF NOT EXISTS bulk_type VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS include_staff TINYINT(1) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS student_count INT DEFAULT 1,
    ADD COLUMN IF NOT EXISTS student_list TEXT NULL,
    ADD COLUMN IF NOT EXISTS staff_list TEXT NULL,
    ADD COLUMN IF NOT EXISTS qr_owner_id VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS receiver_id VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS requested_by_staff_code VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS requested_by_staff_name VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS exit_date_time DATETIME NULL,
    ADD COLUMN IF NOT EXISTS return_date_time DATETIME NULL,
    ADD COLUMN IF NOT EXISTS request_submitted_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS manual_code VARCHAR(10) NULL,
    ADD COLUMN IF NOT EXISTS qr_used TINYINT(1) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS qr_used_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS pass_type VARCHAR(20) DEFAULT 'SINGLE',
    ADD COLUMN IF NOT EXISTS user_type VARCHAR(20) DEFAULT 'STUDENT',
    ADD COLUMN IF NOT EXISTS attachment_uri MEDIUMTEXT NULL,
    ADD COLUMN IF NOT EXISTS qr_code_generated_at DATETIME NULL;

-- Verify all columns exist
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Gatepass'
ORDER BY ORDINAL_POSITION;
